### ISSUE TITLE
cloud you add a callback on io.socket.socketio.server.SocketIoSocket.onEvent(Packet)

### ISSUE THREAD

**Issue by aximo** [trinopoty/socket.io-server-java#1]
i think if you add a new  callback or emit a general event like this:
```
callback.on(event,eventArgs);
emit(event, eventArgs);
```
it will be very helpful if we process messages in a general way.

**Comment by aximo** [comment]
i know that，so i suggest a special java callback interface，emit a special event maybe is not a good choice

**Comment by trinopoty** [comment]
I've added a listener for all events in SocketIoSocket class. You can check it out.
