### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by djamb** [trinopoty/socket.io-server-java#14]
Im trying to use library in android but when im connected to server with client and stop of send data, server restart automatically at few seconds.

**Comment by trinopoty** [comment]
can you make sure the android library you're using is using version 4 or 3 of the protocol.

**Comment by djamb** [comment]
> can you make sure the android library you're using is using version 4 or 3 of the protocol.

Im using 2.x Client version for 3.x Socket.IO server

**Comment by trinopoty** [comment]
Can you link the android library you're using. I'll check it out and make sure my library doesn't have compatibility issues.

**Comment by djamb** [comment]
I'm using my own wrapper of library with annotations, https://github.com/djamb/EasySocketIO based on https://github.com/socketio/socket.io-client-java

**Comment by trinopoty** [comment]
This is taking a while for me to get to. I'll try to diagnose compatibility issues between the client library and this one. Might take a few more days for me to get to it however.

**Comment by djamb** [comment]
> This is taking a while for me to get to. I'll try to diagnose compatibility issues between the client library and this one. Might take a few more days for me to get to it however.

Ty :)

**Comment by trinopoty** [comment]
I've been sitting on this for quite some time now. The java server library follows major versions of the js server library while the java client library does not follow any such convention. So it's left up to the user to check compatibility.
Can you update to the latest version of the libraries and check if the compatibility issue is still there.
