### ISSUE TITLE
tests do not test SocketIoServer

### ISSUE THREAD

**Issue by rfox12** [trinopoty/socket.io-server-java#24]
Hey there, I'm taking a look at socket.io-server-java and in the tests (ServerWrapper) I noticed you've declared mSocketIoServer but it's never actually used in the code.  The test seem to run on Engine.IO with a custom `JettyWebSocketHandler` included from another mysterious java module.  Am I missing something?

**Comment by rfox12** [comment]
Nevermind I think the `socket.io-server-test` must have been some unrelated code, not a test suite for SocketIoServer

**Comment by trinopoty** [comment]
`socket.io-server-test` is essentially integration test which validates the Java library against the JS library which is our source of truth.
Even if `mSocketIoServer` isn't used directly in code, it does a lot of processing on the messages going in and out to the client.
