### ISSUE TITLE
Jetty v11 support

### ISSUE THREAD

**Issue by kgecici** [trinopoty/socket.io-server-java#26]
Hi

Thanks for great implementation.

Do you have any plan for Jetty 11 upgrade?

Since Jetty 11 has "big bang" change, there is no javax.servlet.* it is now jakarta.servlet.*.

So I upgraded in my fork with following jakarta dependency(And many other import changes) I successfully compile Engine.io-server-java and socket.io-server-java. 

But unfortunately, I couldn't pass the socket.io-server-tests since Initialization of websocket has changed dramatically. 

https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-server-http-handler-use-webapp-context
// Setup the ServerContainer and the WebSocket endpoints for this web application context.
        JakartaWebSocketServletContainerInitializer.configure(handler, (servletContext, container) ->
        {
            // Configure the ServerContainer.
            container.setDefaultMaxTextMessageBufferSize(128 * 1024);

            // Simple registration of your WebSocket endpoints.
            //container.addEndpoint(PoCJettyWebsocketHandler.class);

            // JettyWebSocketHandler  Constructor requires args but even if I create empty constructor it does not call methods
            ServerEndpointConfig config = ServerEndpointConfig.Builder.create(JettyWebSocketHandler.class, "/socket.io/")
                    .build();
            container.addEndpoint(config);
        });

Would you help me to run if I create PR?

        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>9.1.0</version>
            <scope>provided</scope>
        </dependency>

**Comment by trinopoty** [comment]
I'd like to upgrade to the new version of the library but I wouldn't want to break any existing users on the older `javax.servlet.*` package.
I'll review how to approach this and bring an update some time in the future.

**Comment by kajtzu** [comment]
"We" also got hit by the this Oracle-keeps-javax-internally-Eclipse-introduces-jakarta mess with socket.io Java server version. Not ideal, I agree.

The best answer on the internet seems to be https://stackoverflow.com/questions/70862464/how-to-use-java-ee-and-jakarta-ee-together which, for TLDR, is not really a good answer as all the answers are suboptimal. Eclipse Transformer works on compiles code, while theoretically (and in practice) solving the problem blindly doing stuff on the byte code level isn't my idea of fun ;) similarly wrapper classes could be written but SO comments note that they won't work with annotations. Etc. etc.

I guess maintaining two different versions won't work, either, as that adds to the maintainer's tasks.

One alternative would be to stop supporting one and start supporting the newer one but I understood between the lines that isn't something that you'd want to do.

**Comment by sparkyspider** [comment]
Hey gentlemen,

We're also using Jetty 11. I don't unfortunately have the brains to figure out how to connect Engine.IO and Socket.IO to Jetty's ContextHolders. SerletContexts, Filters, etc.

It would be really amazing if someone were kind enough to post an example somewhere. 

Is this a possibility?

**Comment by mindlid** [comment]
what about Jetty 12 release around the corner

**Comment by trinopoty** [comment]
Hi,
I'm pleased to announce that the latest version of the library has been upgraded to use jakarta api.
