### ISSUE TITLE
Unable to connect socket-io with socket-io chrome extension

### ISSUE THREAD

**Issue by shifazahera** [trinopoty/socket.io-server-java#28]
Hi  @trinopoty / @oddmario 
I have tried running the demo project - https://github.com/oddmario/socket.io-server-java-demo. I was able to connect to the server with the simple js client as given below
const
    io = require("socket.io-client"),
    ioClient = io.connect("http://localhost:9094");

ioClient.emit("message","Hello Server");
ioClient.on("message", (msg) => console.info(msg));

It is working fine but when I am trying to connect to the server using web-socket client extension of chrome with the following url
ws://localhost:9094/socket.io/?EIO=4&transport=websocket. I am finding out that the connection is not established and the communication is not happening. Can you please help me out how to enable web socket transport so that the server recognizes the connection as ws (web socket) connection instead of http.

**Comment by Krish47007** [comment]
Even I'm also facing the same issue when I'm trying to connect with ws protocol using postman. @trinopoty  can u pls suggest how we can provide transport mechanism as "websocket" or "polling" when we're creating SocketIoServer?

**Comment by SaraAadilKhan** [comment]
Hi @trinopoty
I was trying to do the same but nothing worked. How to send the transport option(whether http/ws), acknowledgement along with that. Requesting you to look into this and provide some solution

**Comment by trinopoty** [comment]
Hi,
I'm not familiar with the execution environment of chrome extensions. Can you set a debug breakpoint and validate that the websocket connection is getting initiated and handled by the server?

The server requires the developer to manually hook the http and websocket handlers, can you please confirm that you've hooked the required method calls properly.

**Comment by trinopoty** [comment]
The library is agnostic to any compression used by the transport layer.
You can push any valid json values in either direction.

**Comment by SaraAadilKhan** [comment]
Thank you @trinopoty for your response

**Comment by SaraAadilKhan** [comment]
Hi @trinopoty 
In future will the websocket compression be supported? 
If yes can you please tell me when can we expect this to be implemented?

**Comment by trinopoty** [comment]
We don't have a timeline for adding compression support. Having said that, we'd be happy to receive a PR implementing compression.

**Comment by SaraAadilKhan** [comment]
Thank you so much @trinopoty for your response
