### ISSUE TITLE
socket.io-client in Android an iOS， kill app socket.io-server can't receive event disconnect

### ISSUE THREAD

**Issue by yingzhifengfeng** [trinopoty/socket.io-server-java#3]
1. Android or iOS App connect to server。
2. kill the App
3.socket.io server can go here
![image](https://user-images.githubusercontent.com/16483888/51718851-187a0d00-2082-11e9-9231-46d5a6fc00a5.png)

4.but can'go here 
![image](https://user-images.githubusercontent.com/16483888/51718915-57a85e00-2082-11e9-9c43-986a802f33e8.png)

**Comment by trinopoty** [comment]
ok. I'll look into it.

**Comment by trinopoty** [comment]
When you kill and android/ios app, you have to wait until the ping timeout for disconnect detection.
In the default configuration, this may be up to 30 seconds.
Can you confirm that you get a disconnect event after waiting 30 seconds?

**Comment by yingzhifengfeng** [comment]
1. i am not set transports
![image](https://user-images.githubusercontent.com/16483888/51728914-e6ca6b80-20ac-11e9-9915-d2f61515f600.png)
2. open the test.html -> close 
3. java console log , never print disconnect event 

4. when i set transports :  ['websocket'] ,only use websocket
5. java console log , print disconnect event , Immediate

6.i use android test ,result the same
7.swift can't set transports

```
@Slf4j
@Configuration
public class SocketIoServiceConfig {

    @Bean
    public EngineIoServer engineIoServer() {
        return new EngineIoServer();
    }

    @Bean
    public SocketIoServer socketIoServer(EngineIoServer engineIoServer) {
        SocketIoServer socketIoServer = new SocketIoServer(engineIoServer);
        SocketIoNamespace namespace = socketIoServer.namespace("/");
        namespace.on("connection", args -> {
            SocketIoSocket socketIoSocket = (SocketIoSocket) args[0];
             log.error("connection socketId is {}", socketIoSocket.getId());

            socketIoSocket.on("disconnecting", args1 -> {
                log.error("disconnecting socketId is {}", socketIoSocket.getId());
            });
            socketIoSocket.on("disconnect", args1 -> {
                log.error("disconnect socketId is {}", socketIoSocket.getId());
            });
            socketIoSocket.on("error", args1 -> {
                log.error("error socketId is {}", socketIoSocket.getId());
            });
        });
        return socketIoServer;
    }
}
```


```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.dev.js"></script>
    <script>
        var host = 'http://localhost:8080';
        var socket = io(host,{
            path: '/socket.io',
            // transports: ['websocket']
        });
        socket.on('connect', function(){
            console.log('connected');
        });
        socket.on('disconnect', function(){
            console.log('disconnect')
        });
        socket.on('error', function(error){
            console.log('error', error);
        });
        socket.on('connect_error', function(error){
            console.log("connect_error", error);
        });
    </script>
</head>
<body>

</body>
</html>
```

**Comment by yingzhifengfeng** [comment]
> When you kill and android/ios app, you have to wait until the ping timeout for disconnect detection.
> In the default configuration, this may be up to 30 seconds.
> Can you confirm that you get a disconnect event after waiting 30 seco

**Comment by trinopoty** [comment]
Did you get a disconnect after 30 seconds?

**Comment by yingzhifengfeng** [comment]
> Did you get a disconnect after 30 seconds?

no
![image](https://user-images.githubusercontent.com/16483888/51729903-7e7d8900-20b0-11e9-8a20-1890b1b55c1a.png)
