### ISSUE TITLE
event emit from server is not working

### ISSUE THREAD

**Issue by amirizzudin4** [trinopoty/socket.io-server-java#30]
hi, I'm using this library together with engine io as socket handler in springboot following this documentation https://socketio.github.io/engine.io-server-java/spring-integration.html . I'm able to get the connection working but, I'm not able to emit anything from the server. I'm only able to send from socket instance but not the server instance. please help if there is any step I'm missing here.

**Comment by trinopoty** [comment]
Are you referring to broadcast to all connections or just to one client?

**Comment by amirizzudin4** [comment]
Im referring to both. The emit functionality is not working at all

**Comment by trinopoty** [comment]
Do you get any exceptions?
Can you check your network tab for related network traffic.
