### ISSUE TITLE
How does one setup an Acknowledgement function?

### ISSUE THREAD

**Issue by realkarmakun** [trinopoty/socket.io-server-java#32]
Right now I listen for an event the following way:
```java
socket.on("createRoom", msgArgs -> {
                try {
                    log.info("[Client %s] requested room creation".formatted(socket.getId()));
                    Room newRoom = new Room(socket.getId());
                    WebServiceBack.INSTANCE.roomList().put(newRoom.roomId(), newRoom);

                    final var responseObj = new CreateRoomResponsePacket(newRoom.roomId(), socket.getId(), createRoomRequest.name());
                    SocketIoSocket.ReceivedByLocalAcknowledgementCallback.
                    socket.send("createRoom", dataToJson(responseObj));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
```

How should I setup  local ack function in the first place?

**Comment by realkarmakun** [comment]
I see two methods for `SocketIoSocket#send`, with and without `ReceivedByRemoteAcknowledgementCallback` argument but I don't see `SocketIoSocket#on` with `ReceivedByLocalAcknowledgementCallback`

Could it be missing?

**Comment by trinopoty** [comment]
`ReceivedByLocalAcknowledgementCallback` is automatically appended to the args when it's requested by the client.
`args[args.length - 1]` would contain `ReceivedByLocalAcknowledgementCallback` if necessary.

**Comment by SZahera** [comment]
Hi @trinopoty 
Does jetty uses netty Internally? No right!

**Comment by trinopoty** [comment]
I'm sure it's mentioned somewhere. I'll update the docs to make it clearer in the next release.
