### ISSUE TITLE
Query Params and Headers

### ISSUE THREAD

**Issue by kalyanam** [trinopoty/socket.io-server-java#4]
Is there a way to obtain socket handshake details via these APIs just like what's available at: https://socket.io/docs/server-api/#socket-handshake?

I'm looking to obtain auth tokens via headers and some query params as well. So, this capability will be really helpful to do that.

**Comment by trinopoty** [comment]
Not directly but since you need to manually add the proper handlers (servlet and websocket), you can access any header or other parameters you need in you servlet (or websocket handler).
It may be difficult to tell if it's a handshake or not though.

**Comment by trinopoty** [comment]
Keeping the handshake request around is not supported because I'm not really sure how that will behave with different server implementations.
