### ISSUE TITLE
Is there a demo for springboot2.x and tomcat?

### ISSUE THREAD

**Issue by jptangchina** [trinopoty/socket.io-server-java#40]
I've tried use @WebServlet("/socket.io/*") and @ServletComponentScan in springboot2.x default with tomcat, but I'm too stupid to make it work, I just can't connet to the server. Could you please help me?

BTW, I'm using socket.io-client.js 4.5.2(latest) as client, and it works fine with the jetty demo.

`@WebServlet("/socket.io/*")
public class SocketServlet extends HttpServlet {

    private final EngineIoServer mEngineIoServer;
    private final SocketIoServer mSocketIoServer;

    public SocketServlet() {
        EngineIoServerOptions options = EngineIoServerOptions.newFromDefault();
        options.setAllowedCorsOrigins(null);
        mEngineIoServer = new EngineIoServer(options);
        mSocketIoServer = new SocketIoServer(mEngineIoServer);
        SocketIoNamespace namespace = mSocketIoServer.namespace("/");
        namespace.on("connection", objects -> {
            // do something
        });
    }

    @Override
    protected void service(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        mEngineIoServer.handleRequest(req, resp);
    }
}`

**Comment by jptangchina** [comment]
I found this guide: https://socketio.github.io/engine.io-server-java/spring-integration.html from other issue, it works fine!

**Comment by handazao** [comment]
> I found this guide: https://socketio.github.io/engine.io-server-java/spring-integration.html from other issue, it works fine!

可以看看你的demo怎麽写的吗，谢谢
