### ISSUE TITLE
Namespaces?

### ISSUE THREAD

**Issue by jonathan-meyer** [trinopoty/socket.io-server-java#5]
Is there an issue with using namespaces other than "/"?

**Comment by jonathan-meyer** [comment]
![image](https://user-images.githubusercontent.com/20321382/81183431-286ae700-8f7d-11ea-9809-c402e7895588.png)

**Comment by trinopoty** [comment]
Namespaces work perfectly find in my experience. I've been using it for quite a while now.
Can you please also show the java side of the code. Your servlet and websocket handler.

**Comment by jonathan-meyer** [comment]
I'm using spring-boot and my code is available here:
https://github.com/stejsoftware/zengine/blob/master/src/main/java/com/stejsoftware/zengine/controller/SocketIoController.java

This test page will show the undesired behavior:
https://zvm.herokuapp.com/socket-test-admin.html

The test page works: 
https://zvm.herokuapp.com/socket-test.html

**Comment by trinopoty** [comment]
There are a couple of issues I found in your code.
1) `ServerConfig.java` You're creating duplicate instances of `EngineIoServer`. Solution: Don't call `engineIoServer()` on line 19. Pass `EngineIoServer` as argument to `socketIoServer` method.
2) You're using spring security module but haven't configured it to `permitAll()` socket.io traffic.

**Comment by jonathan-meyer** [comment]
Ok thanks I'll give those a try.

**Comment by jonathan-meyer** [comment]
This is what I needed:
```
    @Override
    public void configure(WebSecurity web) throws Exception {
        web
            .ignoring()
                .antMatchers(HttpMethod.POST, "/socket.io/**");
    }
```

Thanks!
