### ISSUE TITLE
Acknowledgement callback without namespace

### ISSUE THREAD

**Issue by ken-chen-icsgame** [trinopoty/socket.io-server-java#7]
Server side with Kotlin:

```
	namespace = socketIoServer.namespace("/chat")
	namespace.on("connection") { clients ->
		val client = clients.firstOrNull() as? SocketIoSocket
		client?.on("custom-event") {
			val callback = it.firstOrNull() as? SocketIoSocket.ReceivedByLocalAcknowledgementCallback
			callback?.sendAcknowledgement("hello callback")
		}
	}
```

Client side with TypeScript:

```
	const socket = io("http://myspace:8080/chat", {
		transports: ["websocket"],
	})
	socket.on("connect", () => {
		socket.emit("custom-event", function(data?: any) {
			console.log(data) 
		})
	})
```

Client side emit message:

`42/chat,0["custom-event"]`

**PROBLEM:** 

The Acknowledgement callback event sent by server without namespace:

`430["hello callback"]`

**Comment by trinopoty** [comment]
Looks like I messed up translating the JS code a bit. And since I don't use ack, I've never run across this bug.
I'll push out a fix some time tomorrow.

**Comment by trinopoty** [comment]
The new version `1.0.2` should be available on maven in a few hours.
